<?php

/**
 * @file
 * Adds a checkbox to user login form.
 */

declare(strict_types = 1);

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function show_password_form_user_login_form_alter(
  array &$form,
  FormStateInterface $form_state,
  string $form_id
): void {

  $form['showpass'] = [
    '#type' => 'checkbox',
    '#title' => t('Show Password'),
    '#attributes' => [
      'class' => ['show-pass'],
    ],
  ];

  $form['#attached']['library'][] = 'show_password/reveal';

}
