_core:
  default_config_hash: DIuRxgLzDh82NlGr5h67xrsGSi4HzpJenEqDeWfYKc8
403:
  title: 'Access denied, Not Logged in'
  body: 'You must be logged in to view anything.'
  theme: ''
  enable_login: 1
404:
  title: 'Not found'
  body: 'Requested page not found.'
  theme: ''
  enable_login: 0
redirect: ''
