<?php

use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\user\Entity\User;

/**
 * Implements hook_form_alter().
 *
 * Add cancel button on new node form
 */
function glen_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'node_article_form':
      $form['#title'] = t('New Post');
      $form['actions']['cancel'] = [
        '#type' => 'submit',
        '#submit' => ['glen_button_cancel'],
        '#value' => t('Cancel'),
        '#limit_validation_errors' => [],
        '#weight' => 999,
        '#button_type' => 'cancel',
      ];
      break;
    case 'webform_submission_contact_add_form':
      \Drupal::service('honeypot')->addFormProtection($form, $form_state, ['honeypot', 'time_restriction']);
      break;
    case 'node_article_edit_form':
      break;
  }

}

/**
 * Implements hook_user_format_name_alter().
 */
function glen_user_format_name_alter(&$name, $account) {
  // I don't want to show any names, but still want to show date
  if (!\Drupal::service('router.admin_context')->isAdminRoute()) {
    if ($name != 'editor') {
      $name = '101 Artists Colony';
    }
  }
}

function glen_preprocess_html(&$variables) {
  $current_path = \Drupal::service('path.current')->getPath();
  $path_alias = \Drupal::service('path_alias.manager')->getAliasByPath($current_path);
  $path_alias = ltrim($path_alias, '/');
  $variables['attributes']['class'][] = 'path-' . \Drupal\Component\Utility\Html::cleanCssIdentifier($path_alias);
}

//    \Drupal::messenger()->addMessage('test is: ' . print_r($form));

