<?php

use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\user\Entity\User;

/**
 * Implements hook_user_login().
 */
function glen_user_login(User $user) {
}

function glen_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  if ($form_id === 'node_article_form') {
    $node = $form_state
      ->getFormObject()
      ->getEntity();
    $is_new = $node->isNew();

//    node-article-edit-form
//    \Drupal::messenger()->addMessage('test is: ' . print_r($form));

	    $form['#title'] = $is_new ? t('New Post') : t('Edit Post');
	    str_replace('Article', 'Post', $form['#title']);
  }


/*
  $request = \Drupal::request();
  if ($route = $request->attributes->get(\Symfony\Cmf\Component\Routing\RouteObjectInterface::ROUTE_OBJECT)) {
    $title = \Drupal::service('title_resolver')->getTitle($request, $route);
    if ($title == 'Create Article' ) {
      $route->setDefault('_title', 'New Title');
    }
  }
*/
}
